### ISSUE TITLE
have you made money with this approach?

### ISSUE THREAD

**Issue by huvanile** [essofluffy/Ebay-Textbook-Check#1]

**Comment by ddehueck** [comment]
Hey, I ran this program on and off for about two days and was not able to find anything worth reselling on ebay so no I never made any money. It was fun to make though.

There is room for improvement though. I'd recommend looking at a different site to get resale values from. The web scraping of the historical price was never completely accurate.

**Comment by huvanile** [comment]
Ahh okay.  Bookscouter has an API now, so web scraping isn't needed
anymore.  I think it helps on accuracy too.

Thanks!

**Comment by ddehueck** [comment]
Yea I remember being annoyed with the inaccuracy of the price comparison. An API would've have been really helpful. If you attempt to use this code with the API let me know if you need help.

Cheers!

**Comment by huvanile** [comment]
I'm better with vb.net so I might convert it. Mind if I use that eBay API
key to develop with?

**Comment by ddehueck** [comment]
If it still works, go ahead.
